import numpy as np

from train_lightning import main as train

final_experiments = {
    "small cnn attention": {
        "learning_rate": 0.002,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 1e-06,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.15,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 10,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "cnn_attention",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 128,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": False,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "cnn_dropout": 0.1,
        "attention_dropout": 0.1,
        "positional_encoding_dropout": 0.0,
        "causal": True,
        "flux": False,
        "activation": "ReLU",
        "num_attention_blocks": 5,
        "num_heads": 4,
        "hidden_units": 64,
        "expansion_factor": 4,
        "use_relative_pos": False,
        "down_sample_factor": 4,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
    },
    "large cnn attention": {
        "learning_rate": 0.004,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.01,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.1,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 10,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "cnn_attention",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 160,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": False,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "cnn_dropout": 0.2,
        "attention_dropout": 0.2,
        "positional_encoding_dropout": 0.0,
        "causal": True,
        "flux": False,
        "activation": "ReLU",
        "num_attention_blocks": 10,
        "num_heads": 16,
        "hidden_units": 128,
        "expansion_factor": 4,
        "use_relative_pos": False,
        "down_sample_factor": 4,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
    },
    "small mamba": {
        "learning_rate": 0.004,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.001,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.1,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 15,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "mamba",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 128,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": 0.005,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "d_state": 16,
        "d_conv": 4,
        "expand": 2,
        "cnn_dropout": 0.1,
        "mamba_dropout": 0.5,
        "dense_dropout": 0.5,
        "causal": True,
        "flux": False,
        "backbone": "cnn",
        "activation": "SiLU",
        "n_layers": 3,
        "down_sample_factor": 4,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
        "classifier_dim": 128,
        "hidden_units": 64,
    },
    "large mamba": {
        "learning_rate": 0.0034,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.01,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.1,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 15,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "mamba",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 160,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": 0.005,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "d_state": 16,
        "d_conv": 4,
        "expand": 2,
        "cnn_dropout": 0.3,
        "mamba_dropout": 0.3,
        "dense_dropout": 0.5,
        "causal": True,
        "flux": False,
        "backbone": "cnn",
        "activation": "SiLU",
        "n_layers": 20,
        "down_sample_factor": 4,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
        "classifier_dim": 512,
        "hidden_units": 128,
    },
    "small crnn": {
        "learning_rate": 0.001,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.001,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.1,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 15,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "crnn",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 128,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": 0.005,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
        "down_sample_factor": 4,
        "num_rnn_layers": 3,
        "rnn_units": 64,
        "classifier_dim": 256,
        "cnn_dropout": 0.3,
        "rnn_dropout": 0.1,
        "dense_dropout": 0.2,
        "use_dense": True,
        "causal": True,
        "flux": False,
        "activation": "ReLU",
    },
    "large crnn": {
        "learning_rate": 0.0009,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.1,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.25,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 15,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "crnn",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 96,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": 0.005,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "num_conv_layers": 2,
        "channel_multiplication": 2,
        "down_sample_factor": 4,
        "num_rnn_layers": 3,
        "rnn_units": 256,
        "classifier_dim": 1024,
        "cnn_dropout": 0.4,
        "rnn_dropout": 0.1,
        "dense_dropout": 0.1,
        "use_dense": True,
        "causal": True,
        "flux": False,
        "activation": "ReLU",
    },
    "cnn": {
        "learning_rate": 0.0016,
        "epochs": 50,
        "batch_size": 32,
        "weight_decay": 0.01,
        "beta_1": 0.9,
        "beta_2": 0.999,
        "epsilon": 1e-08,
        "gradient_clip_norm": 0.25,
        "optimizer": "radam",
        "decoupled_weight_decay": True,
        "use_pos_weight": True,
        "ema": "None",
        "scheduler": False,
        "early_stopping": 15,
        "min_save_score": 0.75,
        "test_batch_size": 1,
        "model_settings": "cnn",
        "sample_rate": 44100,
        "hop_size": 441,
        "fft_size": 2048,
        "n_mels": 64,
        "pad_mode": "constant",
        "mel_min": 20.0,
        "mel_max": 16000.0,
        "power": 1,
        "normalize": False,
        "mapping": "Three class",
        "pad_annotations": True,
        "pad_value": 0.5,
        "time_shift": 0.02,
        "beats": False,
        "a2md_penalty_cutoff": 0.7,
        "splits": "(0.8, 0.2, 0.0)",
        "k_folds": 5,
        "fold": 0,
        "full_length_test": True,
        "per_song_sampling": False,
        "num_workers": 8,
        "train_set": "a2md_train",
        "eval_set": "A2MD",
        "test_sets": "('RBMA', 'MDB')",
        "segment_type": "frame",
        "frame_length": 8.0,
        "frame_overlap": 0.0,
        "label_lead_in": 0.25,
        "label_lead_out": 0.1,
        "peak_mean_range": 2,
        "peak_max_range": 2,
        "onset_cooldown": 0.02,
        "detect_tolerance": 0.05,
        "ignore_beats": True,
        "shift_predictions": 0.005,
        "min_test_score": 0.79,
        "pr_points": 50,
        "num_channels": 32,
        "num_residual_blocks": 0,
        "num_feature_layers": 2,
        "channel_multiplication": 2,
        "cnn_dropout": 0.2,
        "dense_dropout": 0.2,
        "causal": True,
        "flux": True,
        "activation": "ReLU",
        "classifier_dim": 256,
        "down_sample_factor": 4,
    },
}


def main():
    for model in ["large mamba", "small crnn", "large crnn", "cnn"]:
        print(f"Running model: {model}")
        config = final_experiments[model]
        scores = []
        for fold in range(1, config["k_folds"]):
            config["fold"] = fold
            _, score = train(
                config=config,
                seed=fold,
                experiment_name="final experiments",
                comment=f"{model} fold {fold}",
            )
            scores.append(score)
        print(f"Scores for folds {config['k_folds']}: {scores}")
        print(f"Stats: {np.mean(scores):.4f} ± {np.std(scores):.4f}")
        print("-" * 50)



if __name__ == "__main__":
    main()
